[supervisord]
nodaemon=true
logfile=/dev/fd/1
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
loglevel=info

[program:octane]
command=php /app/artisan octane:start --server=frankenphp --admin-port=2019 --host=0.0.0.0 --port=80
process_name=%(program_name)s
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stopwaitsecs=10
stopasgroup=true
killasgroup=true

[program:queue-worker]
command=php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600
process_name=%(program_name)s
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stopwaitsecs=10

[program:schedule-worker]
command=php /app/artisan schedule:work
process_name=%(program_name)s
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stopwaitsecs=10
