@extends('layouts.marketplace')
@section('title','CombosPlus — Marketplace')
@section('content')
<section class="bg-slate-950 text-white"><div class="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8">
<span class="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-sm text-blue-200">Marketplace de tiendas independientes</span>
<h1 class="mt-6 max-w-4xl text-4xl font-semibold tracking-tight sm:text-6xl">Descubre tiendas y productos que merecen ser encontrados.</h1>
<p class="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Explora negocios, descubre sus productos y consulta las valoraciones de otros clientes.</p>
<form action="{{ route('marketplace.stores') }}" method="GET" class="mt-8 flex max-w-2xl flex-col gap-3 sm:flex-row"><input name="q" type="search" placeholder="Buscar una tienda..." class="min-h-12 flex-1 rounded-xl border-0 px-4 text-slate-900"><button class="min-h-12 rounded-xl bg-blue-600 px-6 font-semibold hover:bg-blue-500">Explorar tiendas</button></form>
</div></section>
<section class="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div class="flex items-end justify-between gap-4"><div><p class="text-sm font-semibold uppercase tracking-wider text-blue-600">Reputación</p><h2 class="mt-1 text-3xl font-semibold">Tiendas mejor valoradas</h2></div><a href="{{ route('marketplace.stores') }}" class="text-sm font-semibold text-blue-600">Ver todas →</a></div>
<div class="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
@forelse($stores as $store)<a href="{{ route('marketplace.store',$store) }}" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div class="flex items-center gap-4"><div class="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-blue-50 font-bold text-blue-600">{{ mb_strtoupper(mb_substr($store->name,0,1)) }}</div><div class="min-w-0"><h3 class="truncate font-semibold group-hover:text-blue-600">{{ $store->name }}</h3><p class="text-sm text-slate-500">{{ $store->review_count }} opiniones</p></div></div><div class="mt-5 text-sm"><span class="text-amber-500">★</span> <b>{{ number_format((float)$store->rating,1) }}</b></div><p class="mt-3 line-clamp-2 text-sm text-slate-500">{{ $store->description ?: 'Conoce esta tienda en CombosPlus.' }}</p></a>
@empty<div class="col-span-full rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-500">Aún no hay tiendas publicadas. Registra tu negocio y sé de los primeros.</div>@endforelse
</div></section>
<section class="bg-slate-50"><div class="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><p class="text-sm font-semibold uppercase tracking-wider text-blue-600">Descubrimiento</p><h2 class="mt-1 text-3xl font-semibold">Productos mejor valorados</h2>
<div class="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
@forelse($products as $product)<a href="{{ route('marketplace.product',[$product->marketplace_tenant_id,$product->getKey()]) }}" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm hover:shadow-lg"><div class="aspect-[4/3] bg-slate-100">@if($product->image)<img src="{{ asset('storage/'.$product->image) }}" alt="{{ $product->name }}" class="h-full w-full object-contain" loading="lazy">@else<div class="grid h-full place-items-center text-sm text-slate-400">Sin imagen</div>@endif</div><div class="p-5"><h3 class="font-semibold">{{ $product->name }}</h3><div class="mt-3 flex justify-between"><b>{{ '$'.number_format((float)$product->price,2) }}</b><span class="text-amber-500">★ {{ number_format((float)($product->rating ?? 0),1) }}</span></div></div></a>
@empty<div class="col-span-full rounded-2xl border border-dashed border-slate-300 p-10 text-center text-slate-500">Los productos destacados aparecerán aquí.</div>@endforelse
</div></div></section>
<section class="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div class="grid gap-6 md:grid-cols-2"><div class="rounded-3xl bg-slate-900 p-8 text-white"><p class="text-sm font-semibold text-blue-300">Para clientes</p><h2 class="mt-2 text-2xl font-semibold">Opiniones que ayudan a elegir.</h2><p class="mt-3 text-slate-300">Las valoraciones de tiendas y productos serán una parte central de la experiencia.</p></div><div class="rounded-3xl border border-blue-100 bg-blue-50 p-8"><p class="text-sm font-semibold text-blue-700">Para negocios</p><h2 class="mt-2 text-2xl font-semibold text-slate-900">Registra tu tienda fácilmente.</h2><p class="mt-3 text-slate-600">El alta de comercios se diseñará como un proceso simple y progresivo.</p><a href="{{ route('marketplace.register') }}" class="mt-6 inline-flex rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white hover:bg-blue-500">Registrar mi tienda</a></div></div></section>
@endsection